# Generated by Django 5.1.4 on 2025-01-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
